OPENAI_API_KEY = "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"

LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
LANGCHAIN_API_KEY = "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"
LANGCHAIN_PROJECT = "POSTOP_RAG_STREAMLIT"


